version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: snwel-next:local
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
      - LOW_MEM_BUILD=1
      - UV_THREADPOOL_SIZE=1
      - NODE_OPTIONS=--max-old-space-size=512
    restart: unless-stopped
