import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "@/components/AppProviders";
import { getSession } from "@/lib/auth";
import { getAllSettings } from "@/services/admin/setting-service";
import { ListResponse } from "@/types/ApiResponses";
import { Setting } from "@/types/Setting";
import { GeistSans } from 'geist/font/sans'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchSettings = async () => {
  try {
    return await getAllSettings()
  } catch (error) {
    return {} as ListResponse<Setting>
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const settings = await fetchSettings();
  return (
    <html lang="en">
      <body className={GeistSans.className}>
          <AppProviders data={{
            settings: settings.docs
          }} session={session}>
            <div>{children}</div>
          </AppProviders>
      </body>
    </html>
  );
}
