import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProviders from "@/components/AppProviders";
import { getSession } from "@/lib/auth";
import { fetchClient } from "@/lib/fetchClient";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
          <AppProviders session={session}>
            <div>{children}</div>
          </AppProviders>
      </body>
    </html>
  );
}
